//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdquirenteSet
    {
        public string RUT { get; set; }
        public Nullable<decimal> PorcentajeDerechos { get; set; }
        public bool DerechosNoAcreditados { get; set; }
        public int FormularioSetNumeroAtencion { get; set; }
    
        public virtual FormularioSet FormularioSet { get; set; }
    }
}
