//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormularioSet()
        {
            this.PorcentajeDisponible = 100m;
            this.AdquirenteSet = new HashSet<AdquirenteSet>();
            this.EnajenanteSet = new HashSet<EnajenanteSet>();
        }
    
        public int NumeroAtencion { get; set; }
        public string CNE { get; set; }
        public string Comuna { get; set; }
        public string Manzana { get; set; }
        public string Predio { get; set; }
        public string Fojas { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public Nullable<long> NumeroInscripcion { get; set; }
        public Nullable<decimal> PorcentajeDisponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdquirenteSet> AdquirenteSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnajenanteSet> EnajenanteSet { get; set; }
    }
}
