//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormularioSet()
        {
            this.AdquirenteSet = new HashSet<AdquirenteSet>();
            this.EnajenanteSet = new HashSet<EnajenanteSet>();
        }
    
        public int NumeroAtencion { get; set; }
        public string CNE { get; set; }
        public string Comuna { get; set; }
        public string Manzana { get; set; }
        public string Predio { get; set; }
        public string Fojas { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public Nullable<long> NumeroInscripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdquirenteSet> AdquirenteSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnajenanteSet> EnajenanteSet { get; set; }
    }
}
