//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InscripcionesBrDbGrupo06Entities : DbContext
    {
        public InscripcionesBrDbGrupo06Entities()
            : base("name=InscripcionesBrDbGrupo06Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdquirenteSet> AdquirenteSet { get; set; }
        public virtual DbSet<Comunas> Comunas { get; set; }
        public virtual DbSet<EnajenanteSet> EnajenanteSet { get; set; }
        public virtual DbSet<FormularioSet> FormularioSet { get; set; }
        public virtual DbSet<MultipropietarioSet> MultipropietarioSet { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
    }
}
