//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultipropietarioSet
    {
        public int Id { get; set; }
        public string RUT { get; set; }
        public Nullable<decimal> PorcentajeDerechos { get; set; }
        public string Fojas { get; set; }
        public Nullable<long> NumeroInscripcion { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public Nullable<System.DateTime> AñoVigenciaInicial { get; set; }
        public Nullable<System.DateTime> AñoVigenciaFinal { get; set; }
        public string Comuna { get; set; }
        public string Manzana { get; set; }
        public string Predio { get; set; }
    }
}
