//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultipropietarioSet
    {
        public int Id { get; set; }
        public string RUT { get; set; }
        public Nullable<decimal> PorcentajeDerechos { get; set; }
        public string Fojas { get; set; }
        public Nullable<long> NumeroInscripcion { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public Nullable<System.DateTime> AñoVigenciaInicial { get; set; }
        public Nullable<System.DateTime> AñoVigenciaFinal { get; set; }
        public string Comuna { get; set; }
        public string Manzana { get; set; }
        public string Predio { get; set; }
        public int FormularioNumeroAtencion { get; set; }
        public bool DerechosNoAcreditados { get; set; }
    }
}
